name: ejson
description: An EJson serialization library for Dart.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  collection: ^1.17.2
  source_gen: ^1.3.2
  type_plus: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
